CRAFTBEERPI_TELEGRAM_VERSION = Telegram Push Notifications for Craftbeerpi 4
CRAFTBEERPI_TELEGRAM_SITE = $(call github,pascal1404,cbpi4-TelegramPushNotifications,$(CRAFTBEERPI_TELEGRAM_VERSION))
CRAFTBEERPI_TELEGRAM_LICENSE = GPL-3
CRAFTBEERPI_TELEGRAM_LICENSE_FILES = LICENSE
CRAFTBEERPI_TELEGRAM_SETUP_TYPE = setuptools

$(eval $(python-package))
