CRAFTBEERPI_TELEGRAM_VERSION = 33817da5ea8e3ffcb2e5811c0b7f68d026d43f2f
CRAFTBEERPI_TELEGRAM_SITE = $(call github,pascal1404,cbpi4-TelegramPushNotifications,$(CRAFTBEERPI_TELEGRAM_VERSION))
CRAFTBEERPI_TELEGRAM_LICENSE = GPL-3
CRAFTBEERPI_TELEGRAM_LICENSE_FILES = LICENSE
CRAFTBEERPI_TELEGRAM_SETUP_TYPE = setuptools

$(eval $(python-package))
