CRAFTBEERPI_PID_HERMS_VERSION = 8613cd2c5c0ba821559d735f3e5bae51f547af26
CRAFTBEERPI_PID_HERMS_SITE = $(call github,avollkopf,cbpi4-PIDHerms,$(CRAFTBEERPI_PID_HERMS_VERSION))
CRAFTBEERPI_PID_HERMS_LICENSE = GPL-3
CRAFTBEERPI_PID_HERMS_LICENSE_FILES = LICENSE
CRAFTBEERPI_PID_HERMS_SETUP_TYPE = setuptools

$(eval $(python-package))
