CRAFTBEERPI_GPIO_DEPENDENT_ACTOR_VERSION = Allows to switch actors dependent on the state GPIO Inputs (alpha)
CRAFTBEERPI_GPIO_DEPENDENT_ACTOR_SITE = $(call github,avollkopf,cbpi4-GPIODependentActor,$(CRAFTBEERPI_GPIO_DEPENDENT_ACTOR_VERSION))
CRAFTBEERPI_GPIO_DEPENDENT_ACTOR_LICENSE = GPL-3
CRAFTBEERPI_GPIO_DEPENDENT_ACTOR_LICENSE_FILES = LICENSE
CRAFTBEERPI_GPIO_DEPENDENT_ACTOR_SETUP_TYPE = setuptools

$(eval $(python-package))
