CRAFTBEERPI_DEPENDENT_ACTOR_VERSION = Allows to switch actors dependent on the state of other actors
CRAFTBEERPI_DEPENDENT_ACTOR_SITE = $(call github,avollkopf,cbpi4-DependentActor,$(CRAFTBEERPI_DEPENDENT_ACTOR_VERSION))
CRAFTBEERPI_DEPENDENT_ACTOR_LICENSE = GPL-3
CRAFTBEERPI_DEPENDENT_ACTOR_LICENSE_FILES = LICENSE
CRAFTBEERPI_DEPENDENT_ACTOR_SETUP_TYPE = setuptools

$(eval $(python-package))
