CRAFTBEERPI_RECIPE_IMPORT_VERSION = 78b07920029b2cc0dfd96022457c18454a792021
CRAFTBEERPI_RECIPE_IMPORT_SITE = $(call github,avollkopf,cbpi4-RecipeImport,$(CRAFTBEERPI_RECIPE_IMPORT_VERSION))
CRAFTBEERPI_RECIPE_IMPORT_LICENSE = GPL-3
CRAFTBEERPI_RECIPE_IMPORT_LICENSE_FILES = LICENSE
CRAFTBEERPI_RECIPE_IMPORT_SETUP_TYPE = setuptools

$(eval $(python-package))
