CRAFTBEERPI_RECIPE_IMPORT_VERSION = Example Plugin to customize automated recipe creation
CRAFTBEERPI_RECIPE_IMPORT_SITE = $(call github,avollkopf,cbpi4-RecipeImport,$(CRAFTBEERPI_RECIPE_IMPORT_VERSION))
CRAFTBEERPI_RECIPE_IMPORT_LICENSE = GPL-3
CRAFTBEERPI_RECIPE_IMPORT_LICENSE_FILES = LICENSE
CRAFTBEERPI_RECIPE_IMPORT_SETUP_TYPE = setuptools

$(eval $(python-package))
