CRAFTBEERPI_PCF8574_GPIO_VERSION = Extend PI's GPIO Actors by 8 via I2C device
CRAFTBEERPI_PCF8574_GPIO_SITE = $(call github,avollkopf,cbpi4-PCF8574-GPIO,$(CRAFTBEERPI_PCF8574_GPIO_VERSION))
CRAFTBEERPI_PCF8574_GPIO_LICENSE = GPL-3
CRAFTBEERPI_PCF8574_GPIO_LICENSE_FILES = LICENSE
CRAFTBEERPI_PCF8574_GPIO_SETUP_TYPE = setuptools

$(eval $(python-package))
