CRAFTBEERPI_HTTP_ACTOR_VERSION = Generic Craftbeerpi4 HTTP Actor Plugin
CRAFTBEERPI_HTTP_ACTOR_SITE = $(call github,hurra,cbpi4-http-actor,$(CRAFTBEERPI_HTTP_ACTOR_VERSION))
CRAFTBEERPI_HTTP_ACTOR_LICENSE = GPL-3
CRAFTBEERPI_HTTP_ACTOR_LICENSE_FILES = LICENSE
CRAFTBEERPI_HTTP_ACTOR_SETUP_TYPE = setuptools

$(eval $(python-package))
