CRAFTBEERPI_HTTP_ACTOR_VERSION = 0d04d1a5c6653f9b2eb960a721ee156a0f21f66a
CRAFTBEERPI_HTTP_ACTOR_SITE = $(call github,hurra,cbpi4-http-actor,$(CRAFTBEERPI_HTTP_ACTOR_VERSION))
CRAFTBEERPI_HTTP_ACTOR_LICENSE = GPL-3
CRAFTBEERPI_HTTP_ACTOR_LICENSE_FILES = LICENSE
CRAFTBEERPI_HTTP_ACTOR_SETUP_TYPE = setuptools

$(eval $(python-package))
