CRAFTBEERPI_KETTLE_SENSOR_VERSION = 2a20a82a1f47a79641c42f37d55122aaa1cefb58
CRAFTBEERPI_KETTLE_SENSOR_SITE = $(call github,avollkopf,cbpi4-KettleSensor,$(CRAFTBEERPI_KETTLE_SENSOR_VERSION))
CRAFTBEERPI_KETTLE_SENSOR_LICENSE = GPL-3
CRAFTBEERPI_KETTLE_SENSOR_LICENSE_FILES = LICENSE
CRAFTBEERPI_KETTLE_SENSOR_SETUP_TYPE = setuptools

$(eval $(python-package))
