CRAFTBEERPI_KETTLE_SENSOR_VERSION = Collects targettemp and power/status for kettle / fermenter
CRAFTBEERPI_KETTLE_SENSOR_SITE = $(call github,avollkopf,cbpi4-KettleSensor,$(CRAFTBEERPI_KETTLE_SENSOR_VERSION))
CRAFTBEERPI_KETTLE_SENSOR_LICENSE = GPL-3
CRAFTBEERPI_KETTLE_SENSOR_LICENSE_FILES = LICENSE
CRAFTBEERPI_KETTLE_SENSOR_SETUP_TYPE = setuptools

$(eval $(python-package))
