CRAFTBEERPI_FLOWMETER_VERSION = 26fbaa30fd48c75ca48b5af2f51a71ccb359f80f
CRAFTBEERPI_FLOWMETER_SITE = $(call github,avollkopf,cbpi4-Flowmeter,$(CRAFTBEERPI_FLOWMETER_VERSION))
CRAFTBEERPI_FLOWMETER_LICENSE = GPL-3
CRAFTBEERPI_FLOWMETER_LICENSE_FILES = LICENSE
CRAFTBEERPI_FLOWMETER_SETUP_TYPE = setuptools

$(eval $(python-package))
