CRAFTBEERPI_FLOWMETER_VERSION = Hall Sensor based Flowmeter Sensor
CRAFTBEERPI_FLOWMETER_SITE = $(call github,avollkopf,cbpi4-Flowmeter,$(CRAFTBEERPI_FLOWMETER_VERSION))
CRAFTBEERPI_FLOWMETER_LICENSE = GPL-3
CRAFTBEERPI_FLOWMETER_LICENSE_FILES = LICENSE
CRAFTBEERPI_FLOWMETER_SETUP_TYPE = setuptools

$(eval $(python-package))
