CRAFTBEERPI_BM_STEPS_VERSION = Example Plugin for custom Mash steps
CRAFTBEERPI_BM_STEPS_SITE = $(call github,avollkopf,cbpi4-BM_Steps,$(CRAFTBEERPI_BM_STEPS_VERSION))
CRAFTBEERPI_BM_STEPS_LICENSE = GPL-3
CRAFTBEERPI_BM_STEPS_LICENSE_FILES = LICENSE
CRAFTBEERPI_BM_STEPS_SETUP_TYPE = setuptools

$(eval $(python-package))
