CRAFTBEERPI_BM_STEPS_VERSION = ed66cd2dca3a0886ed02d47c381068714ce47fbe
CRAFTBEERPI_BM_STEPS_SITE = $(call github,avollkopf,cbpi4-BM_Steps,$(CRAFTBEERPI_BM_STEPS_VERSION))
CRAFTBEERPI_BM_STEPS_LICENSE = GPL-3
CRAFTBEERPI_BM_STEPS_LICENSE_FILES = LICENSE
CRAFTBEERPI_BM_STEPS_SETUP_TYPE = setuptools

$(eval $(python-package))
