CRAFTBEERPI_TRIAC_HAT_ACTOR_VERSION = e80c162ee66d1c18a1e7159f2b41701f1b45dc69
CRAFTBEERPI_TRIAC_HAT_ACTOR_SITE = $(call github,netanelklein,cbpi4-TriacHatActor,$(CRAFTBEERPI_TRIAC_HAT_ACTOR_VERSION))
CRAFTBEERPI_TRIAC_HAT_ACTOR_LICENSE = GPL-3
CRAFTBEERPI_TRIAC_HAT_ACTOR_LICENSE_FILES = LICENSE
CRAFTBEERPI_TRIAC_HAT_ACTOR_SETUP_TYPE = setuptools

$(eval $(python-package))
