CRAFTBEERPI_ISPINDLE_VERSION = Sensor that collects data from the iSpindle
CRAFTBEERPI_ISPINDLE_SITE = $(call github,avollkopf,cbpi4-iSpindle,$(CRAFTBEERPI_ISPINDLE_VERSION))
CRAFTBEERPI_ISPINDLE_LICENSE = GPL-3
CRAFTBEERPI_ISPINDLE_LICENSE_FILES = LICENSE
CRAFTBEERPI_ISPINDLE_SETUP_TYPE = setuptools

$(eval $(python-package))
