CRAFTBEERPI_ISPINDLE_VERSION = 7d033d93b2c2c46722e0700db30f676bd1db2bfb
CRAFTBEERPI_ISPINDLE_SITE = $(call github,avollkopf,cbpi4-iSpindle,$(CRAFTBEERPI_ISPINDLE_VERSION))
CRAFTBEERPI_ISPINDLE_LICENSE = GPL-3
CRAFTBEERPI_ISPINDLE_LICENSE_FILES = LICENSE
CRAFTBEERPI_ISPINDLE_SETUP_TYPE = setuptools

$(eval $(python-package))
