CRAFTBEERPI_GROUPED_POWERED_ACTOR_VERSION = Allows to group Actors and ramp the power linear over the individual actors
CRAFTBEERPI_GROUPED_POWERED_ACTOR_SITE = $(call github,avollkopf,cbpi4-GroupedPowerActor,$(CRAFTBEERPI_GROUPED_POWERED_ACTOR_VERSION))
CRAFTBEERPI_GROUPED_POWERED_ACTOR_LICENSE = GPL-3
CRAFTBEERPI_GROUPED_POWERED_ACTOR_LICENSE_FILES = LICENSE
CRAFTBEERPI_GROUPED_POWERED_ACTOR_SETUP_TYPE = setuptools

$(eval $(python-package))
