CRAFTBEERPI_GROUPED_POWERED_ACTOR_VERSION = 5631ae2f4de35eefc21727a9bec047258cac2ec1
CRAFTBEERPI_GROUPED_POWERED_ACTOR_SITE = $(call github,avollkopf,cbpi4-GroupedPowerActor,$(CRAFTBEERPI_GROUPED_POWERED_ACTOR_VERSION))
CRAFTBEERPI_GROUPED_POWERED_ACTOR_LICENSE = GPL-3
CRAFTBEERPI_GROUPED_POWERED_ACTOR_LICENSE_FILES = LICENSE
CRAFTBEERPI_GROUPED_POWERED_ACTOR_SETUP_TYPE = setuptools

$(eval $(python-package))
