CRAFTBEERPI_FERMENTERSTEP_VERSION = aa984caced2eac0fbbc6683b8140d9000cf6b24f
CRAFTBEERPI_FERMENTERSTEP_SITE = $(call github,avollkopf,cbpi4_Fermenterstep,$(CRAFTBEERPI_FERMENTERSTEP_VERSION))
CRAFTBEERPI_FERMENTERSTEP_LICENSE = GPL-3
CRAFTBEERPI_FERMENTERSTEP_LICENSE_FILES = LICENSE
CRAFTBEERPI_FERMENTERSTEP_SETUP_TYPE = setuptools

$(eval $(python-package))
