CRAFTBEERPI_DHT22_TEMP_HUM_SENSOR_VERSION = Sensor for Reltive humidity and temperature
CRAFTBEERPI_DHT22_TEMP_HUM_SENSOR_SITE = $(call github,DanZee,cbpi4-dht22-temp-hum-sensor,$(CRAFTBEERPI_DHT22_TEMP_HUM_SENSOR_VERSION))
CRAFTBEERPI_DHT22_TEMP_HUM_SENSOR_LICENSE = GPL-3
CRAFTBEERPI_DHT22_TEMP_HUM_SENSOR_LICENSE_FILES = LICENSE
CRAFTBEERPI_DHT22_TEMP_HUM_SENSOR_SETUP_TYPE = setuptools

$(eval $(python-package))
