CRAFTBEERPI_LCDISPLAY_VERSION = bed64c0cf3cfe104c8c5ba03e7c726cf0db21085
CRAFTBEERPI_LCDISPLAY_SITE = $(call github,JamFfm,cbpi4-LCDisplay,$(CRAFTBEERPI_LCDISPLAY_VERSION))
CRAFTBEERPI_LCDISPLAY_LICENSE = GPL-3
CRAFTBEERPI_LCDISPLAY_LICENSE_FILES = LICENSE
CRAFTBEERPI_LCDISPLAY_SETUP_TYPE = setuptools

$(eval $(python-package))
