CRAFTBEERPI_LCDISPLAY_VERSION = Allows usage of LCD Display (I2C)
CRAFTBEERPI_LCDISPLAY_SITE = $(call github,JamFfm,cbpi4-LCDisplay,$(CRAFTBEERPI_LCDISPLAY_VERSION))
CRAFTBEERPI_LCDISPLAY_LICENSE = GPL-3
CRAFTBEERPI_LCDISPLAY_LICENSE_FILES = LICENSE
CRAFTBEERPI_LCDISPLAY_SETUP_TYPE = setuptools

$(eval $(python-package))
