CRAFTBEERPI_PID_BOIL_VERSION = 58b098127a7d912875716b1a7fb0d0930fe59e48
CRAFTBEERPI_PID_BOIL_SITE = $(call github,avollkopf,cbpi4-PIDBoil,$(CRAFTBEERPI_PID_BOIL_VERSION))
CRAFTBEERPI_PID_BOIL_LICENSE = GPL-3
CRAFTBEERPI_PID_BOIL_LICENSE_FILES = LICENSE
CRAFTBEERPI_PID_BOIL_SETUP_TYPE = setuptools

$(eval $(python-package))
