CRAFTBEERPI_NEXTION_DISPLAY_VERSION = 374f5486d4ba8cb955b0c892e14de1db083780e8
CRAFTBEERPI_NEXTION_DISPLAY_SITE = $(call github,JamFfm,cbpi4-NEXTIONDisplay,$(CRAFTBEERPI_NEXTION_DISPLAY_VERSION))
CRAFTBEERPI_NEXTION_DISPLAY_LICENSE = GPL-3
CRAFTBEERPI_NEXTION_DISPLAY_LICENSE_FILES = LICENSE
CRAFTBEERPI_NEXTION_DISPLAY_SETUP_TYPE = setuptools

$(eval $(python-package))
