CRAFTBEERPI_PID_AUTOTUNE_VERSION = 6bfb9e78929939144e41c78f5bb635002a62aa5c
CRAFTBEERPI_PID_AUTOTUNE_SITE = $(call github,avollkopf,cbpi4-PID_AutoTune,$(CRAFTBEERPI_PID_AUTOTUNE_VERSION))
CRAFTBEERPI_PID_AUTOTUNE_LICENSE = GPL-3
CRAFTBEERPI_PID_AUTOTUNE_LICENSE_FILES = LICENSE
CRAFTBEERPI_PID_AUTOTUNE_SETUP_TYPE = setuptools

$(eval $(python-package))
