CRAFTBEERPI_BUZZER_VERSION = d5265c46f0e103e29536ccdd454a1350117ac6bc
CRAFTBEERPI_BUZZER_SITE = $(call github,avollkopf,cbpi4-buzzer,$(CRAFTBEERPI_BUZZER_VERSION))
CRAFTBEERPI_BUZZER_LICENSE = GPL-3
CRAFTBEERPI_BUZZER_LICENSE_FILES = LICENSE
CRAFTBEERPI_BUZZER_SETUP_TYPE = setuptools

$(eval $(python-package))
