CRAFTBEERPI_SCD30_CO2_SENSOR_VERSION = Temp, Rel. Humidity and CO2 sensor (I2C based)
CRAFTBEERPI_SCD30_CO2_SENSOR_SITE = $(call github,avollkopf,cbpi4-scd30-co2-sensor,$(CRAFTBEERPI_SCD30_CO2_SENSOR_VERSION))
CRAFTBEERPI_SCD30_CO2_SENSOR_LICENSE = GPL-3
CRAFTBEERPI_SCD30_CO2_SENSOR_LICENSE_FILES = LICENSE
CRAFTBEERPI_SCD30_CO2_SENSOR_SETUP_TYPE = setuptools

$(eval $(python-package))
