CRAFTBEERPI_GROUPED_ACTOR_VERSION = d59772e7e40181b0125fe854fc7d3d9a8c1f62bd
CRAFTBEERPI_GROUPED_ACTOR_SITE = $(call github,avollkopf,cbpi4-GroupedActor,$(CRAFTBEERPI_GROUPED_ACTOR_VERSION))
CRAFTBEERPI_GROUPED_ACTOR_LICENSE = GPL-3
CRAFTBEERPI_GROUPED_ACTOR_LICENSE_FILES = LICENSE
CRAFTBEERPI_GROUPED_ACTOR_SETUP_TYPE = setuptools

$(eval $(python-package))
