CRAFTBEERPI_GROUPED_ACTOR_VERSION = Allows to group Actors
CRAFTBEERPI_GROUPED_ACTOR_SITE = $(call github,avollkopf,cbpi4-GroupedActor,$(CRAFTBEERPI_GROUPED_ACTOR_VERSION))
CRAFTBEERPI_GROUPED_ACTOR_LICENSE = GPL-3
CRAFTBEERPI_GROUPED_ACTOR_LICENSE_FILES = LICENSE
CRAFTBEERPI_GROUPED_ACTOR_SETUP_TYPE = setuptools

$(eval $(python-package))
