CRAFTBEERPI_UI_VERSION = Web UI
CRAFTBEERPI_UI_SITE = $(call github,avollkopf,craftbeerpi4-ui,$(CRAFTBEERPI_UI_VERSION))
CRAFTBEERPI_UI_LICENSE = GPL-3
CRAFTBEERPI_UI_LICENSE_FILES = LICENSE
CRAFTBEERPI_UI_SETUP_TYPE = setuptools

$(eval $(python-package))
