CRAFTBEERPI_PUSH_OVER_VERSION = 07c2c5998438042b4a6460f36f7732c9ff4627c4
CRAFTBEERPI_PUSH_OVER_SITE = $(call github,avollkopf,cbpi4-PushOver,$(CRAFTBEERPI_PUSH_OVER_VERSION))
CRAFTBEERPI_PUSH_OVER_LICENSE = GPL-3
CRAFTBEERPI_PUSH_OVER_LICENSE_FILES = LICENSE
CRAFTBEERPI_PUSH_OVER_SETUP_TYPE = setuptools

$(eval $(python-package))
