name: image

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'

env:
  BUILDROOT_VERSION: '2022.05.1'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config:
          - 'craftbeerpi_rpi3'
          - 'craftbeerpi_rpi4'
      fail-fast: false

    env:
      BUILD_NAME: '${{ matrix.config }}-${{ github.sha }}'
      CONFIG_NAME: '${{ matrix.config }}_defconfig'
    steps:
      - name: free space on runner
        run: |
          sudo rm -rf /usr/share/swift /usr/share/dotnet

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install bc

      - name: checkout Buildroot
        uses: actions/checkout@v2
        with:
          repository: 'buildroot/buildroot'
          ref: '${{ env.BUILDROOT_VERSION }}'
          path: 'buildroot'

      - name: checkout external
        uses: actions/checkout@v2
        with:
          path: 'external'

      - name: configure image
        run: |
          make -s BR2_EXTERNAL=$GITHUB_WORKSPACE/external $CONFIG_NAME
        working-directory: 'buildroot'

      - name: Cache Downloads
        id: cache-downloads
        uses: actions/cache@v3
        with:
          path: buildroot/dl
          key: ${{ env.BUILDROOT_VERSION }}-buildroot-dl

      - name: download source
        run: |
          make -s source
        working-directory: 'buildroot'

      - name: build image
        run: |
          make -s all
        working-directory: 'buildroot'

      - name: upload sdcard image
        uses: actions/upload-artifact@v3
        with:
          name: '${{ matrix.config }}-sdcard.img'
          path: buildroot/output/images/sdcard.img
          if-no-files-found: error
