name: release-image

on:
  push:
    tags:
    - "v*"

env:
  BUILDROOT_VERSION: '2022.05.1'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        config:
          - 'craftbeerpi_rpi3'
          - 'craftbeerpi_rpi4'
      fail-fast: false

    env:
      BUILD_NAME: '${{ matrix.config }}-${{ github.ref_name }}'
      CONFIG_NAME: '${{ matrix.config }}_defconfig'
    steps:
      - name: free space on runner
        run: |
          sudo rm -rf /usr/share/swift /usr/share/dotnet
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install bc
      - name: checkout Buildroot
        uses: actions/checkout@v2
        with:
          repository: 'buildroot/buildroot'
          ref: '${{ env.BUILDROOT_VERSION }}'
          path: 'buildroot'

      - name: checkout external
        uses: actions/checkout@v2
        with:
          path: 'external'
          submodules: 'recursive'

      - name: configure image
        run: |
          make -s BR2_EXTERNAL=$GITHUB_WORKSPACE/external $CONFIG_NAME
        working-directory: 'buildroot'

      - name: download source
        run: |
          make -s source
        working-directory: 'buildroot'

      - shell: bash
        env:
          RELEASE_SIGNING_KEY_B64: ${{ secrets.RELEASE_SIGNING_KEY_B64 }}
          RELEASE_SIGNING_CERT_B64: ${{ secrets.RELEASE_SIGNING_CERT_B64 }}
        run: |
          mkdir -p output/images/
          echo $RELEASE_SIGNING_KEY_B64 | base64 -d > output/images/cbpifw-update.key
          echo $RELEASE_SIGNING_CERT_B64 | base64 -d > output/images/cbpifw-update.pem

      - name: build image
        run: |
          make -s all
        working-directory: 'buildroot'

      - name: rename sd card image
        run: |
          mv buildroot/output/images/sdcard.img buildroot/output/images/${BUILD_NAME}.img
      
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "buildroot/output/images/${{ env.BUILD_NAME }}.img"
          prerelease: true
          allowUpdates: true
